[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl", "python3"]

[phases.install]
cmds = ["chmod +x scripts/install-deps.sh && ./scripts/install-deps.sh"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

